run IT

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -37,6 +37,16 @@ jobs:
     steps:
       - checkout
       - run:
+          name: Check presence of requirements.txt
+          command: |
+            if [ ! -f "requirements.txt" ]; then
+              echo "ERROR: requirements.txt not found"
+              exit 1
+            elif [ ! -s "requirements.txt" ]; then
+              echo "ERROR: requirements.txt is empty"
+              exit 1
+            fi
+      - run:
           name: Install dependencies
           command: |
             sudo apt-get update && sudo apt-get install -y \
@@ -104,7 +114,9 @@ jobs:
             unzip
             python -m pip install --upgrade pip
             pip install -r requirements.txt
-      # Agrega aquí los pasos para las pruebas de integración
+      - run:
+          name: Run integration tests
+          command: python -m unittest integration_tests.py
 
   compatibility_tests:
     docker:
